project_id = "vpoqqgnbhqgxikumjitu"

[functions.manage-users]
verify_jwt = false

[functions.bootstrap-admin]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.login]
verify_jwt = false

[functions.generate-scenario]
verify_jwt = false
